### ISSUE TITLE
Solution to Problem #8 does not work

### ISSUE THREAD

**Issue by njhaveri** [AvdAdiVaish/Euler-1-10#1]
https://github.com/AvdAdiVaish/Euler-1-10/blob/e51a6c3fb5829158e352940aec2d32f13b5b1c19/Euler.py#L65

Getting the below error when trying to run in Python REPL
**Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
ValueError: invalid literal for int() with base 10: '<'** 

See the command line trace below:
 
```
>>> num_str = """<insert 1000-digit number here>"""
>>> adjacent_digits = 13
>>> result = 0
>>> for i in range(len(num_str) - adjacent_digits):
...     product = 1
...     for j in range(adjacent_digits):
...         product *= int(num_str[i + j])
...     result = max(result, product)
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
ValueError: invalid literal for int() with base 10: '<'
```

**Comment by njhaveri** [comment]
@AvdAdiVaish Please take a look at this issue.
